# Generated by Django 6.0.2 on 2026-02-20 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['first_name']},
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='students_first_n_73f9e9_idx',
        ),
        migrations.AlterModelTable(
            name='student',
            table=None,
        ),
    ]
