# Generated by Django 5.2.11 on 2026-02-06 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='updated_at',
        ),
    ]
